version: '3.8'

services:
  db:
    image: postgres:17-alpine
    container_name: amardoctor_db
    environment:
      POSTGRES_DB: ${DB_NAME:-amardoctor}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
