services:
  db:
    image: postgres:17-alpine
    env_file:
      - ./core/.env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - amardoctor_net

  core:
    build:
      context: ./core
      dockerfile: Dockerfile
    env_file:
      - ./core/.env
    environment:
      DEBUG: "True"
      ALLOWED_HOSTS: "*"
      CORS_ALLOWED_ORIGINS: http://localhost,http://127.0.0.1,https://*.ngrok-free.app,https://*.ngrok.io
      CSRF_TRUSTED_ORIGINS: http://localhost,http://127.0.0.1,https://*.ngrok-free.app,https://*.ngrok.io
      REDIS_URL: redis://redis:6379/1
      DB_HOST: db
      DB_PORT: "5432"
      CONN_MAX_AGE: "0"
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    networks:
      - amardoctor_net

  redis:
    image: redis:7-alpine
    networks:
      - amardoctor_net

  celery_worker:
    build:
      context: ./core
      dockerfile: Dockerfile
    command: celery -A core worker -l info
    env_file:
      - ./core/.env
    environment:
      DEBUG: "True"
      CELERY_BROKER_URL: redis://redis:6379/1
      CELERY_RESULT_BACKEND: redis://redis:6379/1
      DB_HOST: db
    depends_on:
      - db
      - redis
    networks:
      - amardoctor_net

  celery_beat:
    build:
      context: ./core
      dockerfile: Dockerfile
    command: celery -A core beat -l info
    env_file:
      - ./core/.env
    environment:
      DEBUG: "True"
      CELERY_BROKER_URL: redis://redis:6379/1
      CELERY_RESULT_BACKEND: redis://redis:6379/1
      DB_HOST: db
    depends_on:
      - db
      - redis
    networks:
      - amardoctor_net

  nginx:
    image: nginx:1.27-alpine
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - core
    networks:
      - amardoctor_net

volumes:
  postgres_data:

networks:
  amardoctor_net:
    driver: bridge
