# Generated by Django 6.0.5 on 2026-05-13 09:16

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('paid_held', 'Paid (Held in Escrow)'), ('released', 'Released to Doctor'), ('refunded', 'Refunded to Patient'), ('failed', 'Failed'), ('disputed', 'Disputed')], db_index=True, default='initiated', max_length=20)),
                ('gateway_provider', models.CharField(default='sslcommerz', max_length=50)),
                ('transaction_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('val_id', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('held_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_commission_percentage', models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='Default platform commission percentage (e.g. 15.00 for 15%)', max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Platform Settings',
            },
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='payments_pa_user_id_01767a_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='payments_pa_appoint_6c6442_idx',
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='appointments.appointment'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='payment',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['user', 'status'], name='payments_pa_user_id_92d873_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['appointment', 'status'], name='payments_pa_appoint_bb6d5f_idx'),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
