# Generated by Django 6.0.5 on 2026-06-28 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_no_prescription_required'),
        ('payments', '0002_paymenttransaction_platformsettings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to='appointments.appointment'),
        ),
    ]
