# Generated by Django 6.0.5 on 2026-05-12 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AITriageSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('ai_processing', 'AI Processing'), ('waiting_for_patient', 'Waiting for Patient'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('language', models.CharField(default='en', max_length=10)),
                ('current_step', models.IntegerField(default=1)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('emergency', 'Emergency')], default='low', max_length=10)),
                ('emergency_detected', models.BooleanField(default=False)),
                ('ai_provider', models.CharField(default='gemini', max_length=50)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triage_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AITriageMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('patient', 'Patient'), ('ai', 'AI'), ('system', 'System')], max_length=10)),
                ('message_type', models.CharField(choices=[('symptom', 'Symptom'), ('follow_up_question', 'Follow Up Question'), ('answer', 'Answer'), ('warning', 'Warning'), ('summary', 'Summary'), ('status_update', 'Status Update')], max_length=20)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='triage.aitriagesession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extracted_symptoms', models.JSONField()),
                ('symptom_duration', models.CharField(max_length=255)),
                ('severity_level', models.CharField(max_length=50)),
                ('follow_up_answers', models.JSONField()),
                ('emergency_flags', models.JSONField(blank=True, default=list)),
                ('ai_summary', models.TextField()),
                ('risk_category', models.CharField(max_length=50)),
                ('recommended_specialization', models.CharField(max_length=255)),
                ('triage_score', models.FloatField(blank=True, null=True)),
                ('ai_confidence_score', models.FloatField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_reports', to=settings.AUTH_USER_MODEL)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='triage.aitriagesession')),
            ],
        ),
    ]
