# Generated by Django 6.0.5 on 2026-05-22 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='no_prescription_required',
            field=models.BooleanField(default=False),
        ),
    ]
