# Generated by Django 5.1.6 on 2026-05-14 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('approve', 'Approve'), ('reject', 'Reject'), ('refund', 'Refund'), ('payout', 'Payout'), ('suspension', 'Suspension'), ('unsuspension', 'Unsuspension'), ('login', 'Login'), ('export', 'Export'), ('flag', 'Flag'), ('deactivation', 'Deactivation')], db_index=True, max_length=20)),
                ('target_model', models.CharField(db_index=True, max_length=100)),
                ('target_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('previous_data', models.JSONField(blank=True, null=True)),
                ('new_data', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['actor', 'action_type'], name='audit_logs__actor_i_de7505_idx'), models.Index(fields=['target_model', 'target_id'], name='audit_logs__target__d9b098_idx'), models.Index(fields=['actor', 'created_at'], name='audit_logs__actor_i_36fd5e_idx'), models.Index(fields=['action_type', 'created_at'], name='audit_logs__action__a9b858_idx')],
            },
        ),
    ]
